### PR TITLE
Add `coraza_v3` support.

### PR DESCRIPTION
**Pull request by s3rj1k**
```
Engine,Case,p1,p2,p3,p4,p5,Overall,Overall (human readable)
coraza_v2,Simple GET,96.886,59.888,15.575,9.325,5.176,5205215.470,5.21s
coraza_v2,Simple JSON,177.821,732.599,15.616,11.381,5.204,12729416.667,12.73s
coraza_v2,Simple URlencoded,147.447,101.018,16.280,4.356,5.544,6133816.154,6.13s
coraza_v2,Simple XML,199.400,338.471,23.294,6.473,6.438,9527201.219,9.53s
coraza_v3,Simple GET,10.403,4.079,0.895,0.524,2.605,279965.986,0.28s
coraza_v3,Simple JSON,34.037,141.490,1.404,0.743,4.819,1974267.209,1.97s
coraza_v3,Simple URlencoded,29.734,96.379,0.916,0.587,2.813,1433716.153,1.43s
coraza_v3,Simple XML,22.891,95.444,1.255,0.713,3.808,1361334.245,1.36s
modsec_v3,Simple GET,19.048,35.466,3.000,0.974,30.824,1255999.277,1.26s
modsec_v3,Simple JSON,40.943,119.669,3.667,1.135,44.427,2603702.463,2.60s
modsec_v3,Simple URlencoded,29.416,48.308,3.239,1.011,32.821,1517022.249,1.52s
modsec_v3,Simple XML,34.750,54.784,3.205,0.992,35.476,1688293.700,1.69s
```

### CODE REVIEW

**Comment by s3rj1k** [comment]
@fzipi @jptosso Team, please confirm that I am using **v3** correctly here, numbers look very good and that makes me a bit suspicious.

**Comment by jptosso** [comment]
Looks good, v2 was way slower than v3. It's a massive upgrade and refactor

**Comment by s3rj1k** [comment]
> Looks good

Maybe merge than?)

**Comment by s3rj1k** [comment]
@jptosso Thanks!

**Pull request merged**
