### PR TITLE
Renovate code for newer dep versions.

### PR DESCRIPTION
**Pull request by s3rj1k**
Renovate some code-deps in preparation for v3 engine addition.
(Planning to keep v2 for reference tests)

### CODE REVIEW

**Comment by fzipi** [comment]
The perfect PR will be to setup the ci/cd that proves this works 😎

**Comment by s3rj1k** [comment]
> perfect PR

small steps preferably, works for me locally, I am getting some CSV using mostly stock `coraza.conf-recommended`

**Review by fzipi — APPROVED** [review]
Sgtm

**Comment by fzipi** [comment]
Looking forward to your next contribution!

**Pull request merged**
